apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-http-server
  namespace: simple-http-server
spec:
  replicas: 3
  selector:
    matchLabels:
      app: simple-http-server
  template:
    metadata:
      labels:
        app: simple-http-server
    spec:
      containers:
      - name: simple-http-server
        image: carloshkayser/simple-http-server:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3333
