apiVersion: v1
kind: Service
metadata:
  name: simple-http-server
  namespace: simple-http-server
spec:
  selector:
    app: simple-http-server
  ports:
  - protocol: TCP
    port: 3333
    targetPort: 3333
  type: NodePort
